---
title: "HW06"
author: "Shazreh Hassan (PID: A13743949)"
format: pdf
---

Question: Can you improve this analysis code?
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


## ANSWER: 

```{r}
# goal of function: read each .pdb file, then trim the .pdb file to pick out rows where chain is A and elety is CA

#input: name of pdb file
func <- function(x="4AKE") {                 
  s <- read.pdb(x)
  s.chainA <- trim.pdb(s, chain="A", elety="CA")
  s.b <- s.chainA$atom$b
  plotb3(s.b, sse=s.chainA, type ="l", ylab="Bfactor")
}

```

Test:

```{r}
#to use function, put in name of the pdb file; output should be the corresponding plot
func("1E4Y")

```

